version: '3.8'
services:
  jewelry_app:
    build: 
       context: .
    ports:
      - 8000:8000
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
