# Generated by Django 4.0.4 on 2022-05-05 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_alter_product_date_alter_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=155)),
                ('payment_type', models.CharField(choices=[[1, 'cash'], [2, 'credit']], default=1, max_length=255)),
                ('total_price', models.CharField(max_length=255)),
                ('tax', models.CharField(max_length=255)),
                ('discount', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=755, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductSold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=155)),
                ('price', models.CharField(max_length=155)),
                ('number', models.IntegerField()),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.factor')),
            ],
        ),
    ]
