# Generated by Django 4.0.4 on 2022-05-05 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_factor_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsold',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.factor'),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
