# Generated by Django 4.0.5 on 2022-07-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productsold_factor_alter_productsold_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='payment_type',
            field=models.CharField(choices=[['csh', 'cash'], ['crd', 'credit']], default='csh', max_length=55),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[['co', 'coin'], ['jew', 'jewelry'], ['go', 'gold_bullion']], default='gr', max_length=55),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[['o', 'ons'], ['m', 'methghal'], ['gr', 'geram']], max_length=55),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sold', to='product.factor'),
        ),
    ]
