# Generated by Django 4.0.5 on 2022-07-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_factor_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSold',
            new_name='FactorProduct',
        ),
    ]
