# Generated by Django 4.0.6 on 2022-07-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_productsold_factorproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='total_price',
        ),
        migrations.AddField(
            model_name='factorproduct',
            name='discount',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factorproduct',
            name='tax',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factorproduct',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[['co', 'coin'], ['jew', 'jewelry'], ['go', 'gold_bullion']], default='co', max_length=55),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[['o', 'ons'], ['m', 'methghal'], ['gr', 'geram']], default='gr', max_length=55),
        ),
    ]
