# Generated by Django 4.0.6 on 2022-07-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_factorproduct_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='total_price',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
