# Generated by Django 4.0.6 on 2022-07-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_factor_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
