# Generated by Django 4.0.4 on 2022-05-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[[1, 'coin'], [2, 'jewelry'], [3, 'gold_bullion']], max_length=55),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.IntegerField(choices=[[1, 'ons'], [2, 'methghal'], [3, 'geram']], max_length=15),
        ),
    ]
