# Generated by Django 4.0.4 on 2022-05-05 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_type_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[[1, 'coin'], [2, 'jewelry'], [3, 'gold_bullion']]),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.IntegerField(choices=[[1, 'ons'], [2, 'methghal'], [3, 'geram']]),
        ),
    ]
