# Generated by Django 4.0.4 on 2022-05-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_factor_product_inventory_productsold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='payment_type',
            field=models.IntegerField(choices=[[1, 'cash'], [2, 'credit']], default=1),
        ),
    ]
