# Generated by Django 4.0.4 on 2022-05-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='image',
            field=models.ImageField(default='def.jpg', upload_to='profile_image'),
        ),
    ]
